export const WORDS_OLOGN: string[] = [
  // JavaScript / TypeScript
  "const xs = arr.filter(Boolean).map(x => x.id).slice(0, 10);",
  "const byId = new Map(users.map(u => [u.id, u] as const));",
  "await Promise.all(urls.map(u => fetch(u).then(r => r.json())));",
  "const ok = /^[a-z0-9_-]{3,16}$/i.test(handle.trim());",
  "const sum = nums.reduce((a, b) => a + b, 0) ?? 0;",
  "for (const [k, v] of Object.entries(obj)) console.log(k, v);",
  "const n = Number.parseInt(input, 10); if (!Number.isFinite(n)) throw n;",
  "const res = await fetch('/api/x', { method: 'POST', body: JSON.stringify(p) });",
  "type Tier = 'USER' | 'SUDO' | 'KERNEL' | 'ROOT';",
  "const t = setTimeout(() => ctrl.abort(), 2500); try { await f(); } finally { clearTimeout(t); }",
  "const key = `${userId}:${mode}:${Date.now()}`; cache.set(key, value);",
  "const out = await fetch(url, { headers: { Authorization: `Bearer ${token}` } });",
  "const next = structuredClone(state); next.items.push(item);",
  "const z = new Intl.NumberFormat('en-US', { maximumFractionDigits: 2 }).format(n);",
  "const s = input.replaceAll('\\n', ' ').trim().slice(0, 256);",
  "const url = new URL('/leaderboard', location.origin); url.searchParams.set('mode', mode);",
  "const ok = Object.prototype.hasOwnProperty.call(obj, key);",
  "const v = await import('./heavy').then(m => m.run(x)).catch(() => null);",
  "const ids = [...new Set(rows.map(r => r.user_id).filter(Boolean))];",
  "const ms = Math.round(performance.now()); console.debug('t=', ms);",

  // Python
  "items = [x for x in xs if x and x.get('id') is not None]",
  "data = {k: v for k, v in pairs if k and v is not None}",
  "from collections import Counter; top = Counter(chars).most_common(3)",
  "def clamp(x, lo, hi): return max(lo, min(hi, x))",
  "import re; ok = bool(re.fullmatch(r\"[a-z0-9_-]{3,16}\", handle))",
  "nums = list(map(int, line.split())); total = sum(nums) if nums else 0",
  "with open(path, 'r', encoding='utf-8') as f: text = f.read()",
  "try: v = int(s) \nexcept ValueError: v = 0",
  "sorted_users = sorted(users, key=lambda u: (-u['score'], u['handle']))",
  "from dataclasses import dataclass; @dataclass(frozen=True) class P: x:int; y:int",
  "import json; payload = json.dumps(obj, separators=(',', ':'), ensure_ascii=False)",
  "from math import isfinite; x = float(s); x = x if isfinite(x) else 0.0",
  "def chunks(xs,n): return [xs[i:i+n] for i in range(0,len(xs),n)]",
  "import time; t0=time.perf_counter(); f(); dt=(time.perf_counter()-t0)*1000",
  "import hashlib; h=hashlib.sha256(b).hexdigest(); print(h[:16])",
  "rows = [r for r in rows if r.get('score') is not None][:100]",
  "from urllib.parse import urlencode; q = urlencode({'mode': mode, 'q': term})",
  "path = os.path.join(root, *parts); assert os.path.exists(path)",
  "s = ''.join(ch for ch in s.lower() if ch.isalnum() or ch in '_-')",
  "import statistics as st; sigma = st.pstdev(intervals) if len(intervals)>2 else 999",

  // Rust
  "let mut m: std::collections::HashMap<String, i32> = HashMap::new();",
  "let ok = handle.chars().all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-');",
  "let xs: Vec<_> = it.filter(|x| x.is_some()).map(|x| x.unwrap()).collect();",
  "let s = input.trim().parse::<i64>().unwrap_or_default();",
  "let v = vec![1, 2, 3]; let sum: i32 = v.iter().copied().sum();",
  "let top = counts.iter().max_by_key(|(_, v)| *v).map(|(k, _)| k);",
  "let chunk = bytes.get(i..i+16).unwrap_or(&[]);",
  "match opt { Some(x) => println!(\"{}\", x), None => eprintln!(\"none\") }",
  "let mut rng = rand::thread_rng(); xs.shuffle(&mut rng);",
  "let t = std::time::Instant::now(); do_work(); eprintln!(\"{}\", t.elapsed().as_millis());",
  "let s = format!(\"{}:{}\", user_id, mode); cache.insert(s, value);",
  "let ok = bytes.iter().all(|b| b.is_ascii());",
  "let s = input.lines().next().unwrap_or(\"\").trim().to_string();",
  "let n: usize = s.parse().unwrap_or(0); let v = vec![0u8; n.min(1024)];",
  "let xs: Vec<_> = items.into_iter().filter_map(|x| x).take(100).collect();",
  "use std::cmp::Ordering; xs.sort_by(|a,b| b.score.cmp(&a.score).then(Ordering::Less));",
  "let mut out = String::new(); out.push_str(&format!(\"{}\", value));",
  "let x = std::env::var(\"TOKEN\").ok().unwrap_or_default();",
  "let m = serde_json::to_string(&payload).unwrap_or_else(|_| \"{}\".into());",

  // Go
  "m := map[string]int{}; if _, ok := m[key]; !ok { m[key] = 1 }",
  "ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second); defer cancel()",
  "type Tier string; const (USER Tier = \"USER\"; ROOT Tier = \"ROOT\")",
  "n, err := strconv.Atoi(strings.TrimSpace(s)); if err != nil { n = 0 }",
  "sort.Slice(xs, func(i, j int) bool { return xs[i].Score > xs[j].Score })",
  "b, _ := json.Marshal(payload); req, _ := http.NewRequest(\"POST\", url, bytes.NewReader(b))",
  "for i, r := range s { if r == '\\n' { fmt.Println(i); break } }",
  "if v, ok := m[id]; ok { fmt.Println(v) } else { fmt.Println(\"missing\") }",
  "sum := 0; for _, n := range nums { sum += n }",
  "defer func() { if r := recover(); r != nil { log.Println(\"panic\", r) } }()",
  "q := url.Values{}; q.Set(\"mode\", mode); q.Set(\"limit\", \"100\"); u.RawQuery = q.Encode()",
  "type Pair[T any] struct { K string; V T }",
  "if err := json.NewDecoder(r.Body).Decode(&p); err != nil { http.Error(w, \"bad\", 400) }",
  "b := make([]byte, 16); if _, err := rand.Read(b); err != nil { panic(err) }",
  "if v == 0 { return fmt.Errorf(\"missing: %s\", name) }",
  "t0 := time.Now(); defer func(){ log.Println(time.Since(t0)) }()",
  "if s := strings.TrimSpace(x); s == \"\" { return nil }",
  "xs = append(xs[:i], xs[i+1:]...)",
  "for k := range m { delete(m, k) }",

  // C++
  "std::vector<int> v{1,2,3}; int s = std::accumulate(v.begin(), v.end(), 0);",
  "std::unordered_map<std::string,int> m; if (!m.count(k)) m[k] = 0;",
  "auto it = std::find_if(v.begin(), v.end(), [](auto& x){ return x.id == id; });",
  "std::sort(v.begin(), v.end(), [](auto& a, auto& b){ return a.score > b.score; });",
  "std::string t = s.substr(0, std::min<size_t>(s.size(), 16));",
  "if (n < 0 || n > 1000000) throw std::out_of_range(\"n\");",
  "for (auto& [k, v] : m) std::cout << k << \":\" << v << \"\\n\";",
  "std::optional<int> x = parse(s); if (x) use(*x);",
  "std::unique_ptr<Node> p = std::make_unique<Node>(args);",
  "constexpr int clamp(int x,int lo,int hi){ return x<lo?lo:(x>hi?hi:x); }",
  "std::string_view sv = s; auto pos = sv.find(':'); auto a = sv.substr(0, pos);",
  "if (auto it = m.find(k); it != m.end()) { use(it->second); }",
  "std::vector<std::string> xs; xs.reserve(128);",
  "auto s = std::chrono::steady_clock::now(); work(); auto ms = duration_cast<milliseconds>(now()-s).count();",
  "std::regex re(\"^[a-z0-9_-]{3,16}$\"); bool ok = std::regex_match(h, re);",
  "std::string out; out.append(buf, buf+n); out.shrink_to_fit();",
  "if constexpr (std::is_integral_v<T>) { return x + 1; } else { return x; }",
  "std::optional<double> x = parse(s); double v = x.value_or(0.0);",
  "std::span<const uint8_t> view(bytes.data(), bytes.size());",

  // Bash
  "set -euo pipefail; IFS=$'\\n\\t'; trap 'echo fail >&2' ERR",
  "grep -R \"TODO\" -n src | awk -F: '{print $1\":\"$2}' | head -n 20",
  "curl -sS \"$URL\" | jq -r '.items[] | .id' | sort -u | wc -l",
  "for f in *.log; do tail -n 5 \"$f\" | sed -E 's/\\s+/ /g'; done",
  "export NODE_ENV=production && npm run build && npm run start",
  "if [[ -z \"${TOKEN:-}\" ]]; then echo \"missing\"; exit 1; fi",
  "find . -maxdepth 2 -type f -name \"*.ts\" -print0 | xargs -0 wc -l",
  "python -c 'import uuid; print(uuid.uuid4())' | tr -d '\\n'",
  "git log --oneline --decorate --graph --max-count=10",
  "openssl rand -base64 32 | tr -d '\\n' && echo",
  "node -e \"console.log(require('crypto').randomUUID())\"",
  "printf '%s\\n' \"$x\" | sed -E 's/[^a-z0-9_-]+//g' | head -c 16",
  "awk -F, '{sum+=$2} END{print sum}' data.csv",
  "python - <<'PY'\nimport time; print(int(time.time()*1000))\nPY",
  "git diff --name-only | xargs -I{} echo \"changed: {}\" | head -n 20",
  "cat /proc/cpuinfo 2>/dev/null | grep -m1 'model name' || uname -a",
  "trap 'rm -f \"$tmp\"' EXIT; tmp=$(mktemp); echo hi > \"$tmp\"",
  "test -n \"$TOKEN\" && echo ok || echo missing",
  "jq -r '.items | length' payload.json",

  // SQL
  "select user_id, max(score) as best from leaderboard group by user_id order by best desc;",
  "select * from leaderboard where is_shadowed = false order by score desc limit 100;",
  "create index concurrently if not exists idx_lb_score on leaderboard (score desc);",
  "update leaderboard set user_id = $1 where guest_token = $2 and user_id is null;",
  "select handle, rank_tier from profiles where handle = $1 limit 1;",
  "insert into leaderboard(user_id,wpm,accuracy,mode,score) values ($1,$2,$3,$4,$5);",
  "select mode, count(*) from leaderboard group by mode order by count desc;",
  "delete from leaderboard where created_at < now() - interval '90 days' and is_shadowed = true;",
  "alter table leaderboard enable row level security;",
  "create policy \"read_public\" on leaderboard for select using (is_shadowed = false);",
  "select user_id, mode, max(score) from leaderboard where is_shadowed=false group by user_id, mode;",
  "select handle, rank_tier from profiles order by created_at desc limit 20;",
  "select * from leaderboard where guest_token is not null and user_id is null limit 50;",
  "create view leaderboard_best as select distinct on (user_id, mode) * from leaderboard order by user_id, mode, score desc;",
  "select now() at time zone 'utc' as utc_now;",
  "update profiles set rank_tier = 'SUDO' where user_id = $1;",
  "select percentile_cont(0.95) within group (order by wpm) from leaderboard;",
  "select mode, avg(wpm) from leaderboard where created_at > now()-interval '7 days' group by mode;",
  "delete from leaderboard where is_shadowed=true and created_at < now()-interval '30 days';",
];

