export const WORDS_O1: string[] = [
  "T extends Record<string, unknown> ? keyof T : never",
  "SELECT * FROM t WHERE (a->>'x')::int BETWEEN 7 AND 42 FOR UPDATE",
  "arr.flatMap(x => x?.items?.filter(Boolean) ?? []).slice(0, 20)",
  "(?:^|\\s)([A-Z][a-z]+(?:[A-Z][a-z]+)+)(?=\\b)",
  "fn f<T: Copy + Ord>(xs: &mut [T]) -> Option<T> { xs.sort(); xs.get(0).copied() }",
  "std::collections::BTreeMap::<String, Vec<(u64, i64)>>::new()",
  "go func(ctx context.Context) error { <-ctx.Done(); return ctx.Err() }(ctx)",
  "((x & 0xff) << 24) | ((y & 0xff) << 16) | ((z & 0xff) << 8) | (w & 0xff)",
  "const id = crypto.randomUUID?.() ?? `${Date.now()}-${Math.random().toString(16).slice(2)}`",
  "const ok = !!(u && (u.role === 'admin' || (u.flags?.includes('sudo') ?? false)))",
  "a?.b?.c?.d ?? (() => { throw new Error('missing'); })()",
  "import('node:crypto').then(m => m.createHash('sha256').update(s).digest('hex'))",
  "if (x == null || Number.isNaN(x)) return; if (!Number.isFinite(x)) throw x;",
  "SELECT regexp_replace(lower(handle), '[^a-z0-9_-]+', '', 'g')",
  "with t as (select unnest($1::text[]) as k) select k, count(*) from t group by k",
  "((?:[0-9a-f]{2}:){5}[0-9a-f]{2})|([0-9a-f]{4}\\.){2}[0-9a-f]{4}",
  "const bytes = new Uint8Array(await crypto.subtle.digest('SHA-256', data))",
  "try { await f(); } catch (e) { if (e instanceof DOMException) throw e; }",
  "xs.sort((a, b) => (b.score - a.score) || a.handle.localeCompare(b.handle))",
  "fn parse(s: &str) -> Result<i64, Box<dyn std::error::Error + Send + Sync>>",
  "let v = input.split_whitespace().map(str::parse::<u64>).collect::<Result<Vec<_>, _>>()?;",
  "type X = { [K in keyof T as `get${Capitalize<string & K>}`]: () => T[K] }",
  "const re = /^(?!.*__)([a-z0-9]+(?:[_-][a-z0-9]+)*)$/i",
  "((?=.{8,64}$)(?=.*\\d)(?=.*[A-Z])(?=.*[a-z])(?=.*[^\\w]).*)",
  "SELECT jsonb_path_query_array(doc, '$.items[*] ? (@.ok == true)')",
  "b = (b ^ (b << 13)) >>> 0; b = (b ^ (b >>> 17)) >>> 0; b = (b ^ (b << 5)) >>> 0",
  "((a??0)+(b??0)+(c??0))/Math.max(1,(n??0))|0",
  "const q = new URLSearchParams(Object.entries(p).filter(([,v])=>v!=null) as any)",
  "if [[ \"$s\" =~ ^[a-z0-9_-]{3,16}$ ]]; then echo ok; else echo no; fi",
  "jq -r '.items[] | select(.wpm>100 and .acc>97) | .id' data.json",
  "std::mem::take(&mut buf).into_iter().filter(|b| *b != 0).collect::<Vec<_>>()",
  "Vec::<(u32, f64)>::with_capacity((n as f64).log2().ceil() as usize + 1)",
  "for (i, ch) in s.char_indices() { if ch.is_whitespace() { break } }",
  "template<typename T> using Opt = std::optional<std::reference_wrapper<const T>>;",
  "auto h = std::hash<std::string_view>{}(sv) ^ (seed + 0x9e3779b97f4a7c15ULL);",
  "SELECT * FROM leaderboard WHERE wpm > 100 AND sigma < 8 AND keylog_len > 30",
  "xs.reduce((m, x) => (m.set(x.k, (m.get(x.k) ?? 0) + 1), m), new Map())",
  "const p = (n: number) => (n & -n) === n && n > 0 ? n : (1 << (32 - Math.clz32(n)))",
  "((t >>> 0) / 0xffffffff) * (hi - lo) + lo",
];

